/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vistas;

import datos.SociosDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import negocios.Control;
import objetosNegocio.Barco;
import objetosNegocio.Socio;

public class FrmBarcos extends javax.swing.JFrame {

    private Control control;
    private SociosDAO sociosDAO;

    /**
     * Creates new form FrmBarcos
     */
    public FrmBarcos() {
        initComponents();
        this.control = new Control();
        this.cargarBarcos();
        this.cargarCmb();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbTitulo = new javax.swing.JLabel();
        panBarcos = new javax.swing.JScrollPane();
        tblBarcos = new javax.swing.JTable();
        lbID = new javax.swing.JLabel();
        lbMatricula = new javax.swing.JLabel();
        lbNombre = new javax.swing.JLabel();
        lbNumAmarre = new javax.swing.JLabel();
        lbCuota = new javax.swing.JLabel();
        lbSocio = new javax.swing.JLabel();
        cmbSocios = new javax.swing.JComboBox<>();
        txtId = new javax.swing.JTextField();
        txtMatricula = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumAmarre = new javax.swing.JTextField();
        txtCuota = new javax.swing.JTextField();
        lbBusqueda = new javax.swing.JLabel();
        txtBusqueda = new javax.swing.JTextField();
        btnBuscar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        bntEditar = new javax.swing.JButton();
        btnBorrar = new javax.swing.JButton();
        btnMenu = new javax.swing.JButton();
        lbIcon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Catalogo de Barcos");

        jPanel1.setBackground(new java.awt.Color(187, 209, 234));

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        lbTitulo.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lbTitulo.setText("Barcos");

        panBarcos.setBackground(new java.awt.Color(255, 255, 255));

        tblBarcos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Matricula", "Nombre", "Num. Amarre", "Cuota", "Socio", "ID Socio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        panBarcos.setViewportView(tblBarcos);

        lbID.setText("ID");
        lbID.setToolTipText("");

        lbMatricula.setText("Matricula");
        lbMatricula.setToolTipText("");

        lbNombre.setText("Nombre");

        lbNumAmarre.setText("Num. Amarre");

        lbCuota.setText("Cuota");

        lbSocio.setText("Socio");

        txtId.setEditable(false);
        txtId.setText("0");

        txtNumAmarre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNumAmarreKeyTyped(evt);
            }
        });

        txtCuota.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCuotaKeyTyped(evt);
            }
        });

        lbBusqueda.setText("Buscar");

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        bntEditar.setText("Editar");
        bntEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bntEditarActionPerformed(evt);
            }
        });

        btnBorrar.setText("Borrar");
        btnBorrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBorrarActionPerformed(evt);
            }
        });

        btnMenu.setText("Menú");
        btnMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMenuActionPerformed(evt);
            }
        });

        lbIcon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/vistas/imagenes/icons8-barco-de-carga-40.png"))); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMenu)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(bntEditar)
                .addGap(30, 30, 30)
                .addComponent(btnBorrar)
                .addGap(36, 36, 36))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lbCuota)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lbID)
                                .addComponent(lbMatricula)
                                .addComponent(lbNombre))
                            .addGap(38, 38, 38)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 112, Short.MAX_VALUE))
                                .addComponent(txtNombre)
                                .addComponent(txtMatricula)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(lbNumAmarre)
                            .addGap(18, 18, 18)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtNumAmarre, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                .addComponent(txtCuota))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(lbSocio)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(btnGuardar)
                                .addGap(26, 26, 26)
                                .addComponent(btnCancelar))
                            .addComponent(cmbSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 218, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panBarcos, javax.swing.GroupLayout.PREFERRED_SIZE, 632, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(7, 7, 7)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbIcon)
                                .addGap(30, 30, 30)
                                .addComponent(lbTitulo))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbBusqueda)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 365, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(btnBuscar)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbID)
                    .addComponent(txtId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbMatricula)
                    .addComponent(txtMatricula, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbNombre)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbNumAmarre)
                    .addComponent(txtNumAmarre, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbCuota)
                    .addComponent(txtCuota, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbSocio)
                    .addComponent(cmbSocios, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnGuardar)
                    .addComponent(btnCancelar))
                .addGap(130, 130, 130))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbTitulo)
                    .addComponent(lbIcon))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbBusqueda)
                    .addComponent(txtBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panBarcos, javax.swing.GroupLayout.PREFERRED_SIZE, 334, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bntEditar)
                    .addComponent(btnBorrar)
                    .addComponent(btnMenu))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNumAmarreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNumAmarreKeyTyped
        char a = evt.getKeyChar();
        if (!Character.isDigit(a)) {
            evt.consume();
        }

    }//GEN-LAST:event_txtNumAmarreKeyTyped

    private void txtCuotaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCuotaKeyTyped
        char a = evt.getKeyChar();
        if (Character.isLetter(a) && a != '.') {
            evt.consume();
        }

    }//GEN-LAST:event_txtCuotaKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        this.cargarBarcos();
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        if (this.txtId.getText().equals("0")) {
            if (!(this.txtMatricula.getText().isEmpty())
                    && !(this.txtNombre.getText().isEmpty()) && this.cmbSocios.getSelectedIndex() != 0
                    && !(this.txtCuota.getText().isEmpty()) && !(this.txtNumAmarre.getText().isEmpty())) {
                this.guardarBarco();
                this.limpiarFormulario();
            }else{
                JOptionPane.showMessageDialog(this, "Deben llenarse todos los datos", "Alerta", JOptionPane.WARNING_MESSAGE);
            }

        } else {
            this.actualizarBarco();
            this.limpiarFormulario();
        }

        
        this.cargarBarcos();

    }//GEN-LAST:event_btnGuardarActionPerformed

    private void bntEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bntEditarActionPerformed
        this.cargarBarco();
    }//GEN-LAST:event_bntEditarActionPerformed

    private void btnBorrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBorrarActionPerformed
        this.eliminarBarco();
        this.cargarBarcos();
    }//GEN-LAST:event_btnBorrarActionPerformed

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.limpiarFormulario();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnMenuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMenuActionPerformed
        this.setVisible(false);
        Menu menu = new Menu();
        menu.setVisible(true);
    }//GEN-LAST:event_btnMenuActionPerformed

    /**
     * @param args the command line arguments
     */
    private void cargarBarcos() {
        List<Barco> barcos = this.control.obtenerBarcos(txtBusqueda.getText());
        if (barcos != null) {
            DefaultTableModel modelo = (DefaultTableModel) tblBarcos.getModel();
            //borra los registros
            modelo.setRowCount(0);
            for (Barco barco : barcos) {
                modelo.addRow(barco.toArray());
            }
        }

    }

    private void cargarCmb() {
        Socio seleccione = new Socio();
        seleccione.setNombre("Seleccione");
        cmbSocios.addItem(seleccione);
        List<Socio> socios = this.control.obtenerSocios(txtBusqueda.getText());
        if (socios != null) {
            for (Socio socio : socios) {
                cmbSocios.addItem(socio);
            }
        }
    }

    private void guardarBarco() {
        Barco barco = new Barco();
        barco.setNombre(txtNombre.getText());
        barco.setCuota(Float.valueOf(txtCuota.getText()));
        barco.setMatricula(txtMatricula.getText());
        barco.setNumAmarre(Integer.parseInt(txtNumAmarre.getText()));
        barco.setSocio((Socio) cmbSocios.getSelectedItem());
        this.control.guardarBarco(barco);
    }

    private void limpiarFormulario() {
        txtId.setText("0");
        txtNombre.setText(" ");
        txtCuota.setText("");
        txtNumAmarre.setText("");
        txtMatricula.setText("");
        this.cmbSocios.setSelectedIndex(0);

    }

    private void actualizarBarco() {
        Barco barco = new Barco();
        barco.setId(Integer.parseInt(txtId.getText()));
        barco.setNombre(txtNombre.getText());
        barco.setCuota(Float.valueOf(txtCuota.getText()));
        barco.setMatricula(txtMatricula.getText());
        barco.setNumAmarre(Integer.parseInt(txtNumAmarre.getText()));
        barco.setSocio((Socio) cmbSocios.getSelectedItem());
        this.control.actualizarBarco(barco);
    }

    private void cargarBarco() {
        int fila = this.tblBarcos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un barco", "información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) this.tblBarcos.getModel();
            Integer idBarco = (Integer) modelo.getValueAt(fila, 0);
            Barco barco = this.control.consultarBarcoPorId(idBarco);
            if (barco != null) {
                txtId.setText(barco.getId().toString());
                txtNombre.setText(barco.getNombre());
                txtMatricula.setText(barco.getMatricula());
                txtCuota.setText(barco.getCuota().toString());
                txtNumAmarre.setText(barco.getNumAmarre().toString());
                cmbSocios.setSelectedItem(barco.getSocio());
            } else {
                JOptionPane.showMessageDialog(this, "No se encontró al barco", "Alerta", JOptionPane.WARNING_MESSAGE);
            }
        }
    }

    private void eliminarBarco() {
        int fila = this.tblBarcos.getSelectedRow();
        if (fila == -1) {
            JOptionPane.showMessageDialog(this, "Debes seleccionar un barco", "información", JOptionPane.INFORMATION_MESSAGE);
        } else {
            DefaultTableModel modelo = (DefaultTableModel) this.tblBarcos.getModel();
            Integer idBarco = (Integer) modelo.getValueAt(fila, 0);
            boolean eliminacionExitosa = this.control.eliminarBarco(idBarco);
            if (eliminacionExitosa) {
                JOptionPane.showMessageDialog(this, "Barco eliminado correctamente", "Informacion", JOptionPane.INFORMATION_MESSAGE);
            } else {
                JOptionPane.showMessageDialog(this, "No se pudo eliminar al barco", "Informacion", JOptionPane.ERROR_MESSAGE);

            }
        }

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bntEditar;
    private javax.swing.JButton btnBorrar;
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnMenu;
    private javax.swing.JComboBox<Socio> cmbSocios;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbBusqueda;
    private javax.swing.JLabel lbCuota;
    private javax.swing.JLabel lbID;
    private javax.swing.JLabel lbIcon;
    private javax.swing.JLabel lbMatricula;
    private javax.swing.JLabel lbNombre;
    private javax.swing.JLabel lbNumAmarre;
    private javax.swing.JLabel lbSocio;
    private javax.swing.JLabel lbTitulo;
    private javax.swing.JScrollPane panBarcos;
    private javax.swing.JTable tblBarcos;
    private javax.swing.JTextField txtBusqueda;
    private javax.swing.JTextField txtCuota;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtMatricula;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumAmarre;
    // End of variables declaration//GEN-END:variables
}
